services:
  alrp:
    image: ghcr.io/alexandershelega/alrp-local:main
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./images:/app/images
    container_name: alrp-service
    environment:
      - TZ=UTC
